### ISSUE TITLE
Create Quiz API

### ISSUE THREAD

**Issue by Vijaydosth** [niyazhussain/quizz#2]
Request Parameters:
1. CategoryID -> int
2. SubCategoryID -> int
3. Question -> string
4. Options -> [string]
5. Snippet -> string
6. ReferenceURL -> string

**Comment by Vijaydosth** [comment]
@niyazhussain @Vijaydosth

**Comment by niyazhussain** [comment]
> mutation {
>   createQuestion(topicId: "5eb2e0bce92fa12f24b000b4", 
>     question:"assaasassas",
>   type: TEXT) {
>     question
>   }
> }
>

**Comment by niyazhussain** [comment]
@Vijaydosth  Refer http://api.quizz.softdefine.com/graphql for create question api
